jpd002/Play-

README.md
The landing page for this project would benefit from a README. A simple one has been included in this commit.
This could be expanded to include the Road Map or extended description on the About web page.
=> Add a simple README.md

Source/COP_VU.cpp, Source/COP_VU.h
http://www.pouet.net/prod.php?which=52237
This doesn't get it fully working, but it gets it running. The video output is a bit jittery, and the torus is glitchy.
=> Get Torus by Lukasz running

build_android/build.xml, build_android/build_debug.sh, build_android/build_release.sh, build_android/custom_rules.xml
=> Android build and hardware support

Source/ui_ios/iCade-iOS/LICENSE, Source/ui_ios/iCade-iOS/iCadeReaderView.h, Source/ui_ios/iCade-iOS/iCadeReaderView.m, Source/ui_ios/iCade-iOS/iCadeState.h, build_ios/Play.xcodeproj/project.pbxproj
Changed to just integrating iCade.
=> Integrate (updated) iCade library

Source/ui_android/java/com/virtualapplications/play/SettingsActivity.java, build_android/res/values/donottranslate.xml, build_android/res/values/strings.xml, build_android/res/values/styles.xml
Adds a dark purple theme to the theme selector options.
=> Add dark purple theme option.

Source/ui_android/java/com/virtualapplications/play/MainActivity.java, Source/ui_android/java/com/virtualapplications/play/NavigationDrawerFragment.java
mDrawerListView.post() might seem weird, I think it is anyway, but thats the only way i found for setting the selection highlight on startup, every otherway returns a null.
=> Android:save user sort preference, highlight user selection on startup, display sort selection in NavBar subtitle

Source/ui_android/java/com/virtualapplications/play/database/TheGamesDB.java
I've done a couple of tests to find out what's taking the longest to complete during the initial start-up and found the code to import the database takes a full minute to complete.
So, I messed around and tested few different methods to see what can be done.
I tried using applyBatch() & bulkInsert() each with their own variation, such as using insert() inside the beginTransaction() just so I can avoid having to read each value from  ContentValues variable to set bind.... etc
but this reminded the fastest method.... it can do the full database import in a single second :)
combine this with the new search method (the one in the index PR), the very 1st clean initial launch of the app would take a full 2 seconds to complete.
Edit:
beginTransaction() causes any operation that is requested from …
=> Android:Database Import improvement

Source/ui_android/java/com/virtualapplications/play/Constants.java, Source/ui_android/java/com/virtualapplications/play/GameInfoEditActivity.java, Source/ui_android/java/com/virtualapplications/play/MainActivity.java, Source/ui_android/java/com/virtualapplications/play/NavigationDrawerFragment.java, Source/ui_android/java/com/virtualapplications/play/ThemeManager.java, build_android/AndroidManifest.xml
getColor was crashing with the new library and so i was replaced it.
Edit: I've also noticed as i was working on the new permission system, that Internet permission is no longer required, as such only 1 permission was needed with this new system.
Edit2:
should have mentioned, for this to work, you'd also need support library v4/v7 updated to 23, and I've made a PR for them as well https://github.com/jpd002/Play-Dependencies/pull/4.
=> Android permission

Source/ScreenShotUtils.cpp, Source/ScreenShotUtils.h, Source/gs/GSH_OpenGL/GSH_OpenGL.cpp, Source/gs/GSH_OpenGL/GSH_OpenGL.h, Source/gs/GSHandler.cpp, Source/gs/GSHandler.h, Source/ui_macosx/ApplicationDelegate.h, Source/ui_macosx/ApplicationDelegate.mm, Source/ui_macosx/English.lproj/MainMenu.xib, Source/ui_unix/ElidedLabel.cpp, Source/ui_unix/ElidedLabel.h, Source/ui_unix/mainwindow.cpp, Source/ui_unix/mainwindow.h, Source/ui_win32/MainWindow.cpp, Source/ui_win32/MainWindow.h, Source/ui_win32/Res.rc, Source/ui_win32/resource.h, build_cmake/CMakeLists.txt, build_unix/mainwindow.ui
This PR also requires [This](https://github.com/jpd002/Play--Framework/pull/11) PR in Framework repo
as such it won't build correctly until that's also merged, so i provided a build log below
[Appveyor](https://ci.appveyor.com/project/Thunder07/play/build/97) & [Travis](https://travis-ci.org/Thunder07/Play-/builds/203220817) builds
Edit: on ubuntu, the screenshot would be saved in `/home/__USER/.local/share/Play..../screenshots/*` which isn't ideal as `.local` is a hidden directory.
but on both OSX/Win32 they're saved into their equivalent of `~/Documents/Play.../screenshots/`
Edit2: ~~just found `MarkNewFrame`, I'll need to test it instead of the signal I added~~
=> Screenshot Feature

.travis.sh
this should help avoid build failures due to failed deployment on forks
=> Skip travis deployment

.gitignore, Source/ui_android/java/com/virtualapplications/play/MainActivity.java
This aims to resolve a few issues with compatibility for "the rest of us"
=> Time format compatibility, Cleanup

Source/ui_android/java/com/virtualapplications/play/database/GameInfo.java
This ensures the stream is complete before attempting close without the
risk to kill off the functionality if close cannot be processed.
=> Close stream after process without risking fail

Source/ui_android/java/com/virtualapplications/play/ThemeManager.java, build_android/src/main/res/values/donottranslate.xml, build_android/src/main/res/values/strings.xml, build_android/src/main/res/values/styles.xml
Updated colour pattern, added new colour and a small cleanup
=> Android color

Source/ui_android/java/com/virtualapplications/play/GameInfoEditActivity.java, Source/ui_android/java/com/virtualapplications/play/ImageUtils.java, Source/ui_android/java/com/virtualapplications/play/database/GameInfo.java
Calculate sample size without having to rely on ImageView.
move the common image sampling function to it's own class.
=> Android Cleanup

Source/ui_unix/CMakeLists.txt, Source/ui_unix/ControllerConfig/controllerconfigdialog.cpp, Source/ui_unix/ControllerConfig/controllerconfigdialog.h, Source/ui_unix/ControllerConfig/inputeventselectiondialog.cpp, Source/ui_unix/ControllerConfig/inputeventselectiondialog.h, Source/ui_unix/GamePad/GamePadDeviceListener.cpp, Source/ui_unix/GamePad/GamePadDeviceListener.h, Source/ui_unix/GamePad/GamePadDeviceListener_OSX.cpp, Source/ui_unix/GamePad/GamePadDeviceListener_OSX.h, Source/ui_unix/GamePad/GamePadInputEventListener.cpp, Source/ui_unix/GamePad/GamePadInputEventListener.h, Source/ui_unix/GamePad/GamePadUtils.cpp, Source/ui_unix/GamePad/GamePadUtils.h, Source/ui_unix/InputBindingManager.cpp, Source/ui_unix/mainwindow.cpp, Source/ui_unix/mainwindow.h
Just tested with linux, beside the 2 commit that I have pushed, everything else is fine.
=> Qt OSX Gamepad

Source/iop/Iop_McServ.cpp, Source/iop/Iop_McServ.h
=> Implement CMcServ::GetEntSpace()... allows Drakengard to detect MC and create saves

Source/gs/GSH_OpenGL/CMakeLists.txt, Source/ui_qt/CMakeLists.txt, Source/ui_qt/GSH_OpenGLQt.cpp
related changes https://github.com/jpd002/Play--Framework/pull/21 https://github.com/jpd002/Play--Framework/pull/22
=> Opengl/GLES selection 

Source/gs/GSH_OpenGL/CMakeLists.txt, Source/ui_android/CMakeLists.txt, Source/ui_ios/CMakeLists.txt
requires https://github.com/jpd002/Play--Framework/pull/23
=> handle OpenGL linking in FrameworkOpenGL

Source/ui_qt/mainwindow.cpp
this should make it easier to track down version associated with screenshot reports (I know I'm guilty of this myself :p)
=> Add version to title

Source/BasicBlock.cpp, Source/ee/MA_VU_Upper.cpp, Source/ee/VuExecutor.cpp
#795 I think I created the warning correctly.  Let me know if there are any issues.
=> Dark cloud assert fixes

Source/ui_shared/CMakeLists.txt
This makes packaging on *nix easier.
=> Use system nlohmann_json library if available

Source/ui_shared/TheGamesDbClient.cpp
this is currently throwing an exception causing the entire process to fail
=> dont fail to load game info, if it has no overview

Source/s3stream/AmazonS3Client.cpp, Source/ui_qt/CoverUtils.cpp, Source/ui_qt/Qt_ui/bootablelistdialog.ui, Source/ui_qt/S3FileBrowser.cpp, Source/ui_qt/bootablelistdialog.cpp, Source/ui_qt/bootablelistdialog.h, Source/ui_shared/AmazonS3Utils.cpp, Source/ui_shared/AmazonS3Utils.h, Source/ui_shared/BootablesDbClient.cpp, Source/ui_shared/BootablesDbClient.h, Source/ui_shared/BootablesProcesses.cpp, Source/ui_shared/CMakeLists.txt
this other PR is not required, to merge this PR anymore, but should be once done, to ensure all games can be list ~~requires https://github.com/jpd002/Play--Framework/pull/27 to correctly list/load all games~~
side note: I tried to get this to work on Android, however, that requires `Framework::HashUtils::ComputeHmacSha256` which in turns requires openssl.
alternatively, we could call android java methods from cpp to get the same results.
=> Qt List S3 bootables

Source/gs/GSHandler.cpp
based on this fix https://github.com/PCSX2/pcsx2/pull/3279
closes #851
fixes `netgui.elf`
=> Mask GS Regs

Source/gs/GSH_Direct3D9/GSH_Direct3D9.cpp, Source/gs/GSH_OpenGL/GSH_OpenGL.cpp
Fixes loading screen not rendering in Burnout 3 (its still stuck tho)
Vulkan implementation is missing as I lack required hardware.
before
after
=> Implement missing blendmode 1002

README.md
Added other packages needed in the instructions for Ubuntu builds.
=> Updated README for Ubuntu builds

Source/PS2VM.cpp, Source/PS2VM_Preferences.h, Source/iop/Iop_Ioman.cpp, Source/ui_qt/vfsmodel.cpp
=> add rom0, host0 devices

Source/iop/Iop_Ioman.cpp, Source/iop/Iop_Ioman.h
Enables [Mafia](https://github.com/jpd002/Play-Compatibility/issues/258) to boot - it checks for a specific error code
=> Implement FileNotFoundException in CIoman

Source/ee/Dmac_Channel.cpp
DMA always transfers at least one QW, regardless of whats in the QWC register. If QWC is 0, it actually underflows the QWC register after sending the first QW.
Enter the Matrix migitates this, as it sets QWC every frame.
Thanks to refraction for checking this on real hardware!
=> Handle DMA transfers with 0 QWC

Source/gs/GSH_OpenGL/GSH_OpenGL.cpp, Source/ui_qt/DebugSupport/DebugView.cpp, Source/ui_qt/DebugSupport/DebugView.h, Source/ui_qt/DebugSupport/FrameDebugger/GsPacketData.cpp, Source/ui_qt/DebugSupport/FrameDebugger/GsPacketData.h, Source/ui_qt/DebugSupport/FrameDebugger/GsPacketListModel.cpp, Source/ui_qt/DebugSupport/FrameDebugger/GsPacketListModel.h, Source/ui_qt/DebugSupport/FrameDebugger/QtFramedebugger.cpp, Source/ui_qt/DebugSupport/FrameDebugger/QtFramedebugger.h, Source/ui_qt/DebugSupport/FunctionsView.cpp, Source/ui_qt/DebugSupport/FunctionsView.h, Source/ui_qt/DebugSupport/QtDebugger.cpp
addresses issues mention in #997 
closes #997
=> Qt debugger Fixes

Source/ui_qt/DebugSupport/FrameDebugger/QtFramedebugger.cpp, Source/ui_qt/DebugSupport/FrameDebugger/QtFramedebugger.h, Source/ui_qt/DebugSupport/FrameDebugger/Qt_ui/QtFramedebugger.ui
=> framedebugger: StepVu1: add menu option & keyboard shortcut(F10)

Source/ui_qt/DebugSupport/MemoryViewTable.cpp, Source/ui_qt/DebugSupport/MemoryViewTable.h
related #997 
Cells will resize to content, thus wont show ellipsis on MacOS due to different font processing.
=> let Qt handle Cell sizes

.github/workflows/build-windows.yaml, .github/workflows/build-windows_psf.yaml
you can see this working in the build https://github.com/Zer0xFF/Play-/runs/1858340527?check_suite_focus=true (checkout step "Set SHORT_HASHtest"), but this should ideally be tested on a different branch on your end before master.
also, since appvoyer config was nuked, it seems you'd need to manually disable it on your own account.
=> fix s3 upload on windows github actions

.github/workflows/build-android.yaml
note, i dont have keystore set on my repo, so its probably best to push this to a branch to make sure its working correctly, though it is a small fix and should work just fine.
=> Fix android signed artifact upload

.gitlab-ci.yml
Hi there,
as per my discussion with @Zer0xFF , here is a PR for the Gitlab CI file that we'll be needing in order to build cores from this repository. Thanks in advance.
=> (Libretro) Add .gitlab-ci.yml

build_android/src/main/res/values-ru/strings.xml
=> (Android) add values-ru/strings

.github/CI_MISC/pre_qt_universal_build.py
Quick note:
* I dont know if this is the "correct" fix for a os install, as comparing the generated libraries (ARM) to installed (x86) ones, we see that we have different paths, aka these use `@rpath/blah`, while installed ones have absolute path (though this shouldnt matter as we're not preparing these for install, but packaging)
* the resulting output from otool is almost identical with 1 noticable difference (when inspected with `otool -l`)
* framework libs : `LC_RPATH` `@loader_path/../../..`
* plugins libs:  `LC_RPATH` `@loader_path/../../lib`
* these paths are ordered after `LC_CODE_SIGNATURE` which might cause issue with signature verifcation?
* I also can't make sense of these paths, so not sure if they're even needed?
I dont have an M1 to test with, so 🤞
related: #988
=> MacOS: update rpath for ARM64 builds

Source/ui_qt/DebugSupport/FrameDebugger/GsContextView.cpp
Also works for CLUT textures which resolve to PSMCT32
=> Add alpha view for PSMCT32 in framedebugger

Source/iop/Iop_McServ.cpp, Source/iop/Iop_McServ.h
Fixes Resident Evil 4 not being able to save
=> Implement WriteFast for McServ

Source/iop/Iop_SifCmd.cpp
Makes Test Drive Unlimited boot (takes very long to load, and gets stuck at logo screen - so just a small fix)
=> Add iSifSendCmdIntr

Source/iop/Iop_Sysclib.cpp, Source/iop/Iop_Sysclib.h
Fixes Max Payne 2 segfault after intro cinematic (game is still broken, but progresses a bit further now)
=> Implement strtoul in sysclib

Source/ee/DMAC.cpp, Source/iop/Iop_Dmac.cpp, Source/iop/Iop_Dmac.h, Source/iop/Iop_Dmacman.cpp, Source/iop/Iop_Dmacman.h
Some collected DMAC stuff I was working on.
- DMAC D3, D5 and D8 TADR writing and reading 
- DMAC DPCR3
- DMACMAN calls 14 - 19
=> DMAC / DMACMAN additions

Source/MIPSAssembler.h
Hi, been getting the following error with the past few commits: https://buildbot.alucryd.xyz/#/builders/287/builds/155/steps/8/logs/stdio
The compiler was kind enough to print the fix.
=> add missing include

Source/ui_android/java/com/virtualapplications/play/ExternalEmulatorLauncher.java, Source/ui_android/java/com/virtualapplications/play/MainActivity.java, Source/ui_android/java/com/virtualapplications/play/database/GameInfo.java, build_android/src/main/res/values/strings.xml
I cleaned up the AlertDialog code because it was wrought with redundancy :)
=> [Android] Clean up AlertDialogs

Source/ui_android/java/com/virtualapplications/play/Bootable.java, Source/ui_android/java/com/virtualapplications/play/EmulatorActivity.java, Source/ui_android/java/com/virtualapplications/play/EmulatorDrawerFragment.java, Source/ui_android/java/com/virtualapplications/play/ExternalEmulatorLauncher.java, Source/ui_android/java/com/virtualapplications/play/GamesAdapter.java, Source/ui_android/java/com/virtualapplications/play/ImageUtils.java, Source/ui_android/java/com/virtualapplications/play/InputManagerConstants.java, Source/ui_android/java/com/virtualapplications/play/MainActivity.java, Source/ui_android/java/com/virtualapplications/play/NavigationDrawerFragment.java, Source/ui_android/java/com/virtualapplications/play/ThemeManager.java, Source/ui_android/java/com/virtualapplications/play/VirtualPadButton.java, Source/ui_android/java/com/virtualapplications/play/VirtualPadStick.java, Source/ui_android/java/com/virtualapplications/play/VirtualPadView.java, Source/ui_android/java/com/virtualapplications/play/database/GameIndexer.java, Source/ui_android/java/com/virtualapplications/play/database/GameInfo.java
=> Some Android code lint cleanup

build_android/src/main/res/values-zh/strings.xml
=> Update langueage strings.

Source/ee/DMAC.cpp
Fixes [AirBlade](https://github.com/jpd002/Play-Compatibility/issues/831) not booting.
=> Add misaligned D9_CHCR read

Source/iop/Iop_Ioman.cpp
Adds a few directory related calls to the ioman invoke function. These are used by OPL to do some MC things.
=> Add ioman directory calls to invoke function

Source/iop/Iop_SifCmd.cpp, Source/iop/Iop_SifCmd.h
Makes Hitman Contracts and Hitman Blood Money progress a bit further, but still not quite boot
=> Implement SifCmd call 7 (SifSetSreg)

Source/CMakeLists.txt, Source/iop/IopBios.cpp, Source/iop/IopBios.h, Source/iop/Iop_PowerOff.cpp, Source/iop/Iop_PowerOff.h
Makes ScummVM boot, if LIBSD is provided in rom0
=> Add PwrOff IOP module stub

Source/iop/Iop_Ilink.cpp, Source/iop/Iop_Ilink.h
Some collected things I had laying around. Mostly derived from debugging some OPL stuff months ago.
=> iLink improvements

Source/iop/Iop_McServ.cpp, Source/iop/Iop_McServ.h
Fixes Operation WinBack 2 memory card access
=> Delay all McServ commands

Source/iop/IopBios.cpp, Source/iop/Iop_SifCmd.h
Fixes Golden Eye Rogue Agent stuck on loading screen
=> Unregister SIF RPC servers on IOP reset

Source/ee/DMAC.cpp, Source/ee/Dmac_Channel.cpp
=> Mask reading from m_D_ENABLE

Source/BasicBlock.cpp, Source/CMakeLists.txt, Source/discimages/CsoImageStream.cpp, Source/discimages/IszImageStream.cpp, Source/ee/EeExecutor.cpp, Source/ee/VuExecutor.cpp, Source/ui_qt/mainwindow.cpp, tools/PsfPlayer/Source/PsfBase.cpp, tools/PsfPlayer/Source/PsfFs.cpp
requires https://github.com/jpd002/Play--Framework/pull/38, https://github.com/jpd002/Play-Dependencies/pull/34 to work correctly
Benchmarks with zlib
Saving x100 = 74919 ms (749ms each)
Loading x100 = 10092 ms (100ms each)
with zstd
Saving x100 = 17155 ms (171ms each)
Loading x100 = 4461 ms (44ms each)
notable change in save speeds.
=> use zstd zlibwrapper for save states 

Source/ui_android/java/com/virtualapplications/play/MainActivity.java, Source/ui_android/java/com/virtualapplications/play/NavigationDrawerFragment.java, build_android/src/main/res/values-ko/strings.xml, build_android/src/main/res/values-pt-rBR/strings.xml, build_android/src/main/res/values-ru/strings.xml, build_android/src/main/res/values-zh-rCN/strings.xml, build_android/src/main/res/values-zh-rTW/strings.xml, build_android/src/main/res/values/donottranslate.xml, build_android/src/main/res/values/strings.xml
- Android: Update language strings and zh translation.
Please Mr. @jpd002 check this PR.
=> Android: Update language strings and zh translation.

Source/hdd/ApaDefs.h
Fix compilation with GCC 13.2.1.
=> add missing header

.gitlab-ci.yml
Fix linux name for it to be picked up by packaging
=> Fix 32-bit linux name

Source/AppConfig.cpp, Source/AppConfig.h, Source/InputConfig.cpp, Source/Log.cpp, Source/PS2VM.cpp, Source/ScreenShotUtils.cpp, Source/ee/Ee_SubSystem.cpp, Source/iop/Iop_Ioman.cpp, Source/iop/Iop_NamcoArcade.cpp, Source/ui_qt/CoverUtils.cpp, Source/ui_shared/BootablesProcesses.cpp, tools/McServTest/AppConfig.cpp, tools/McServTest/AppConfig.h, tools/McServTest/CMakeLists.txt, tools/PsfPlayer/Source/AppConfig.cpp, tools/PsfPlayer/Source/AppConfig.h
Add a "portable.txt" file to the root of Play to use the "Play Data Files" folder in the program folder.
=> Update AppConfig.cpp - portable mode

Source/ee/IPU.cpp
As per the manual, TH0 and TH1 are 9 bits wide.
Simply increasing this mask would break the intro scene to [TearRingSaga Series: Berwick Saga](http://redump.org/disc/25812/)
The second part of the PR fixes that, by properly resetting TH0 and TH1 when IPU_CTRL.RST is set
You can test this as well by using this program
[ipu_th100.zip](https://github.com/jpd002/Play-/files/12471174/ipu_th100.zip)
PR:
MASTER:
PS2: (Excuse the poor photography, I haven't had time to set my stuff up properly)
Related PCSX2 issue and PR
https://github.com/PCSX2/pcsx2/issues/6057
https://github.com/PCSX2/pcsx2/pull/8001
=> IPU: Implement hardware-tested threshold behavior

Source/MIPS.cpp, Source/MIPS.h, Source/MemoryMap.h
=> Fix typos in `Source`

Source/ee/IPU.cpp
=> Fix error: ‘clamp’ is not a member of ‘std’

Source/ui_android/java/com/virtualapplications/play/BootablesInterop.java, Source/ui_android/java/com/virtualapplications/play/NavigationDrawerFragment.java
It seems I missed few android related changes. (I assume there are iOS changes as well that would need to be updated :S)
=> Cleanup/Fix: Fix list order list to reflect new ordering, use new pref name for sorting
