jpd002/Play-

- .gitignore
- build_win32/MipsTest.vcxproj
- build_win32/MipsTest.vcxproj.filters
- build_win32/VuTest.vcxproj
- build_win32/VuTest.vcxproj.filters
This fixes the test projects being dirty every time you build, and also ignores another project.
By the way, I would recommend having some instructions on how to setup the build.  It seems like a bit of a pain.  It's great when users are able to easily build the project because they can provide test results and even debugging results for games you don't own.  Just my opinion.
-[Unknown]
> Cleanup test project files a bit

- Source/CsoImageStream.cpp
- Source/CsoImageStream.h
- Source/IszImageStream.h
- Source/PS2VM.cpp
- Source/macosxui/ApplicationDelegate.mm
- Source/macosxui/VfsManagerBindings.mm
- Source/win32ui/FileFilters.h
- build_win32/Play.vcxproj
- build_win32/Play.vcxproj.filters
I don't have UltraISO, and searching for isz casually didn't yield any alternative compressors.  Since I already [wrote a CSO compressor](https://github.com/unknownbrackets/maxcso) for PPSSPP (though there are many slower ones available), I figured it'd be pretty easy to add support for CSO files.
CSOs are block based and fairly simple.  Some tools may not be able to handle > 4GB files, since PSP games could not be larger than 1.8GB, but this patch can, and so can maxcso (well, after a fix I just made to it.)
IMHO it might be nice to put the different ImageStreams into their own directory, though.
(this implementation is mostly just PPSSPP's implementation, although that one reads full sectors so I changed some things.  It also has larger disk reads when reading more bytes, but I didn't …
> Add support for CSO compressed files

- build_win32/AutoTest.vcxproj
- build_win32/MipsTest.vcxproj
- build_win32/Play.vcxproj
- build_win32/PlayCore.vcxproj
- build_win32/VuTest.vcxproj
This makes it build faster and use more cores.  The same should be done in the Framework, Codegen, etc. dependencies.
-[Unknown]
> Enable multiprocessor compile in all MSVC projects

- Source/ui_android/java/com/virtualapplications/play/VirtualPadButton.java
- Source/ui_android/java/com/virtualapplications/play/VirtualPadView.java
Adds multitouch support to the Android on-screen controls. Buttons are assigned pointer IDs so when the pointer ID assigned to a button is released, that button is released too.
> Android multitouch support

- Source/ui_android/java/com/virtualapplications/play/EmulatorActivity.java
- Source/ui_android/java/com/virtualapplications/play/MainActivity.java
Just some small changes to how the navigation buttons act in the Android UI:
-On devices with on-screen navigation buttons, the navigation buttons will be hidden during emulation allowing for the full screen to be used
-In the file browser, pressing the back button will bring the user to the parent directory instead of just closing the app
> Android: Some changes to navigation bar functions

- Source/ui_android/java/com/virtualapplications/play/EmulatorActivity.java
- Source/ui_android/java/com/virtualapplications/play/MainActivity.java
- build_android/res/layout/emulator.xml
- build_android/res/layout/main_menu.xml
- build_android/res/values/strings.xml
By default the option is disabled. I didn't think one option was enough to create an entire settings menu yet, so I just added a checkable item to the menu in the file browser, under About.
> Android: Add a setting to enable or disable FPS

- Source/PS2VM.cpp
- Source/ee/Ee_SubSystem.cpp
- Source/ee/Ee_SubSystem.h
- Source/ee/Vpu.h
See issue #60 
This PR makes the vpu objects heap allocated rather than stack allocated so that they can be injected at runtime rather than having their type fixed at compile time. This enables a user of the core library to provide specialised implementations (to enable enhanced features for specific games as an example).
I've tried to keep the changes in this PR as minimal as possible. I'm also open to other implementations that would provide similar configurability.
A 'better' or at least a more conventional solution would be to specify the m_vpux objects using a pure abstract interface rather than the heavyweight CVpu class. Currently any alternative implementation needs to extend CVpu - which is quite heavyweight. The downside with that approach of course is that all calls over the …
> Injectable vpu

- Source/ui_android/java/com/virtualapplications/play/MainActivity.java
(With regards to the issue #84)
This quick fix allows files in any case to be picked up by the file explorer by forcing the file names to lower case for the check
> Android version to accept any case file extensions

- Source/PS2VM.h
- Source/ee/MA_VU_Upper.cpp
- Source/ee/Vif1.cpp
- Source/iop/Iop_DmacChannel.h
- Source/iop/Iop_SifCmd.h
- Source/iop/Iop_SifManPs2.h
- Source/iop/Iop_SpuBase.h
there are other things which need to be changed such as "$ANDROID_SDK_ROOT/tools/android.bat to $ANDROID_SDK_ROOT/tools/android" but that would break builds on windows.
however, with that said, I've successfully built "Play!" and installed it on my phone using Ubuntu.
> Ubuntu: Fixed Case-sensitive Build Error

- Source/ui_android/java/com/virtualapplications/play/EmulatorActivity.java
Not sure, why, but every now and then this causes problems in my build.
Well, the problem is, the ui it's trying to access wasn't created yet, but every know and then it works.
Just so, you should probably give the UI time to startup before attempting to access it.
you can also, use Startup() which is called after OnCreate but before OnPostCreate, but since non of these methods are time-critical, this is just as good.
> Android:Moved UI operation until after creating.

- Source/ui_android/java/com/virtualapplications/play/database/GameInfo.java
- Source/ui_android/java/com/virtualapplications/play/database/GamesDbAPI.java
while this solution isn't ideal, as it doesnt give the user the freedom to reset any mismatched title.
that isn't a huge issue at the moment, since they can't do so anyway, irrespective of this fix.
to test this, checkout a game such as Marvel vs Capcom 2.
the noticed difference is that its cover takes longer to load each launch, since it has no database entry associated with its serial, it make an online request for the cover everytime.
> Android: associate missing serials with a database entry

- Source/ui_android/java/com/virtualapplications/play/MainActivity.java
- Source/ui_android/java/com/virtualapplications/play/database/GameInfo.java
- build_android/res/values/strings.xml
Alternative to #297 that overcomes a few issues created while solving scroll lag:
Does not require an excess Singleton class (Uses the existing database / cache)
Does not delay the initial load until the image is available (Initialize the view, fill as loaded)
Supports using Async task (Parallel loading and thread safe)
This has not been fully tested against a large list of games for this emulator (since I don't have a lot of games), but it has been tested against a large collection of images for other lists and grids.
> Add an LruCache to resolve scrolling redraw

- Source/ui_android/java/com/virtualapplications/play/MainActivity.java
- Source/ui_android/java/com/virtualapplications/play/SettingsActivity.java
- Source/ui_android/java/com/virtualapplications/play/database/GameInfo.java
- build_android/res/layout/main.xml
- build_android/res/layout/settings_toolbar.xml
- build_android/res/values/dimens.xml
- build_android/res/values/styles.xml
with transparency removed, we're no longer colouring the statusbar with the actionbar (since it was transparent, the actionbar colour showed behind the statusbar).
I also want to point out, that we can simplify ChangeTheme() a bit more by using this
```TypedArray a = mContext.getTheme().obtainStyledAttributes(new int[]{R.attr.colorPrimary});
int attributeResourceId = a.getColor(0, 0);
a.recycle();```
however, the same logic, can be used backwards, and instead of calling R.attr.colorPrimaryDark, we can define it as a colour and call it through R.color.action_bar_Blue_Dark. initial the reason for me setting it as a resource that it was just easier to call R.color.mycolor instead of the above code
Edit:
if there is a commit you don't need/want, let me know and I'll remove it, or you can …
> Android: Theme statusbar fix

- Source/ui_android/java/com/virtualapplications/play/MainActivity.java
if long click is not reset, it will be associated with another view that does not set a new long click, such as ELFs.
> Android:Fix:reset long click

- build_android/res/values/strings.xml
this string also exists in donttranslate.xml
it also prevents Android Studio from building, with duplicate strings error.
> Android:remove duplicate string

- Source/ui_android/java/com/virtualapplications/play/ExternalEmulatorLauncher.java
- Source/ui_android/java/com/virtualapplications/play/MainActivity.java
- Source/ui_android/java/com/virtualapplications/play/VirtualMachineManager.java
- Source/ui_android/java/com/virtualapplications/play/database/GameInfo.java
- build_android/AndroidManifest.xml
This just moves the External Emulator Launcher to a separate activity, it mostly functions to keep the code uncluttered.
but it also does offer the possibility to customizing the luncher name to external.
however, a small notice, if the main app was launched and then closed (using the home button), then a game is launched through an external launcher, after that game is exited, the main up would show up.
however, I expect people using an external launcher wouldn't be a frequent users for the main ui.
> Android: Seperate Activity For FilePickers/External Emulator Launcher

- build_android/jni/Application.mk
hi All android x86_64 roms launched so far have a bug in build.prop
ARMv8 prioritize binary load before the 32-bit x86 version if x86_x64 binary not exist.
This bug is fixed in the latest android-x86 6.0 branch source git updates a few days ago.
We needed  add x86_64 binary for prevent this error in bug build.prop roms.
> Enable x86_64 Android

- Source/iop/ArgumentIterator.cpp
- Source/iop/ArgumentIterator.h
- Source/iop/Iop_Stdio.cpp
- Source/iop/Iop_Stdio.h
- Source/iop/Iop_Sysclib.cpp
- Source/iop/Iop_Sysclib.h
The code is mainly a duplicate of the existing printf code. The printf code could be refactored to use vsprintf in a similar manner that the standard library does. For anyone not familiar with the emulator wondering why we don't just call the system vsprintf - the problem is that any %s argument will be a ps2 pointer and so needs converting to a real host pointer before it is de-referenced.
> implement vsprintf. Lego starwars uses it in its sound driver.

- Source/MIPS.h
- Source/ee/VuBasicBlock.cpp
Deal with the special case where an integer register is written immediately before a conditional branch which uses it. Fixes Lego star wars.
> Lego spike

- build_macosx/Play.xcodeproj/project.pbxproj
Have the Xcode project refer to files by relation to groups.
Remove Xcode config files from copy phase: they aren't used there.
> Xcode fixes.

- Source/ui_macosx/ApplicationDelegate.mm
- Source/ui_macosx/OutputWindowController.h
- Source/ui_macosx/OutputWindowController.mm
- Source/ui_macosx/VfsManagerBindings.h
- Source/ui_macosx/VfsManagerBindings.mm
- Source/ui_macosx/VfsManagerViewController.mm
This patches quiet warnings when compiled on Xcode 8.1.
It also fixes the Objective-C initialization methods to better match current best practices.
> Madd's Mac Patches

- Source/ui_unix/mainwindow.cpp
- Source/ui_unix/mainwindow.h
I just noticed that on both Win32/OSX the Game ID is displayed on the title bar, while on this PR I have it set to status bar, if you've issue with that I can have it changed.
> Linux: GameID in status bar

- build_cmake/CMakeLists.txt
with Multi-Processes Build enabled Appvoyer now builds the project in 5 minutes compared to 12 minutes previously
> Win32 cleanup

- Source/ee/PS2OS.cpp
- build_cmake/CMakeLists.txt
Current Issue with this build PR, starting a game creates a small/empty non-closable window, restarting the game or a new game causes that window to grow to cover the full screen.... is that an issue you had before? (quick note: lexical_cast wasn't included from boost and noticed one of your earlier commit, so i just followed suit and replaced it)
over the weekend, I've been attempting to setup windows Debugger build as it was setup in visual studio. i.e: `cmake --build . --config Debug/ReleaseWithDebugger` however I've ran into issues, as that would create different build per config, and cmake didn't support that ( there is a work around, but that would involve wrapping the debugger source (aka`DEBUG_SRC` in `CMakeLists.txt`) with `#ifdef debugger_included`).
e.g how that would look …
> CMake Debugger build

- Source/ui_android/java/com/virtualapplications/play/MainActivity.java
- build_android/build.gradle
Someone posted about this not working correctly on G+ community.
Not sure when this broke, but if i had to guess it was with the gradle upgrade.
I've added the build hour into the date as well, as it might be useful should you release multiple updates within the same day.
I got this fix from StackOverflow [post](http://stackoverflow.com/questions/3540739/how-to-programmatically-read-the-date-when-my-android-apk-was-built)
> Android: build date fix

- Source/ui_android/java/com/virtualapplications/play/GameInfoEditActivity.java
- Source/ui_android/java/com/virtualapplications/play/GameInfoStruct.java
- Source/ui_android/java/com/virtualapplications/play/GamesAdapter.java
- Source/ui_android/java/com/virtualapplications/play/MainActivity.java
- Source/ui_android/java/com/virtualapplications/play/SettingsActivity.java
- Source/ui_android/java/com/virtualapplications/play/database/GameIndexer.java
- Source/ui_android/java/com/virtualapplications/play/database/GameInfo.java
- Source/ui_android/java/com/virtualapplications/play/database/GamesDbAPI.java
- Source/ui_android/java/com/virtualapplications/play/database/IndexingDB.java
- Source/ui_android/java/com/virtualapplications/play/database/SqliteHelper.java
- Source/ui_android/java/com/virtualapplications/play/database/TheGamesDB.java
- build_android/src/main/res/layout/activity_gameinfo_edit.xml
- build_android/src/main/res/layout/game_list_item.xml
- build_android/src/main/res/xml/settings_ui_fragment.xml
continuation of the other cleanup [PR](https://github.com/jpd002/Play-/pull/575).
While, I can't separate the commits, I'm opening a separate PR, to allow you to review the changes separately if you so wish.
```
TODO:Adding the serial to the database this way is not ideal, as a mismatch will persist
but as it stands that's the only way to get the pcitures and prevent them from being downloaded every run
```
this is probably the most important change, I believe `games.db` should be considered a read only reference, so we're no longer storing info to it.
> Android cleanup

- patches.xml
Add 4 fix for 4 games.
Note : The ONI fix is only compatible with the pal FR version, and the fix for the Incredibles and Spongebob games are for NTSC-U versions.
> Fix for ONI , The Incredibles , The Incredibles rise of the Underminer and Spongebob the movie.

- Readme.html
Add a warning about the instruction set.
Play! don't support instruction set under SSSE3.
> CPU instruction set warning (readme)

- Source/ui_unix/controllerconfigdialog.cpp
- Source/ui_unix/controllerconfigdialog.h
- Source/ui_unix/inputeventselectiondialog.cpp
- Source/ui_unix/inputeventselectiondialog.h
- build_unix/inputeventselectiondialog.ui
added 3 second button registration window when configuring gamepad, this allows us to remove the 2 second sleep i previously added to avoid the same button getting registered multiple time.
I've removed direct calls to UI when configuration controllers as that was on occasion causing crashes.
lastly, control filter that was setup to prevent certain buttons from spamming the configuration also prevented the range condition `if (value < midVal + triggerVal && value > midVal - triggerVal)` from triggering, so now we'll check the last 20% of the range, which allows us enough range to set an on/off region
edit, you also asked to maybe move the gamepad files our of `ui_unix`, would framework be a better place?
> Qt gamepad cleanup master

- Source/ui_macosx/OutputWindowController.h
- Source/ui_macosx/PreferencesWindowController.h
- Source/ui_macosx/VfsManagerBindings.h
As a general rule, delegates and `IBOutlets` are `weak`, `NSString`s should be `copy`.
> Better ObjC property declarations.

- Source/saves/Icon.h
Replaced deprecated include. Should compile not only on the newest boost version, but on old ones as well.
> Updated boost include

- Source/ui_android/java/com/virtualapplications/play/database/GameIndexer.java
Forgot you guys were still using my pre-Android Studio version of this, so here is the update that does not append the String onto itself (reduces writes and fixes an Android Studio lint warning) and prevents a lint warning by adding something into the catch block (even if it still isn't used at runtime).
> Android: Fix / optimize external sdcard code

- Source/ui_android/java/com/virtualapplications/play/database/GameInfo.java
- Source/ui_android/java/com/virtualapplications/play/database/GamesDbAPI.java
- Source/ui_ios/CoverViewController.m
the current api will be completely removed in time for now we're slow preparing to replace the current(aka old) site with the beta(new) site as such the main domain name will eventually drop the old api, and the legacy domain name will be available during the transition stage to the new api.
P.S. Legacy subdomain will also be eventually be put offline, but by then I'd have PR for it as well.
> Update TheGamesDB to legacy domain

- Source/gs/GSH_OpenGL/GSH_OpenGL.cpp
- Source/gs/GSH_OpenGL/GSH_OpenGL.h
- Source/ui_android/SettingsManager.cpp
- Source/ui_android/SettingsManager.h
- Source/ui_android/java/com/virtualapplications/play/SettingsActivity.java
- Source/ui_android/java/com/virtualapplications/play/SettingsManager.java
- Source/ui_ios/Base.lproj/Main.storyboard
- Source/ui_ios/CMakeLists.txt
- Source/ui_ios/ResolutionFactorSelectorViewController.h
- Source/ui_ios/ResolutionFactorSelectorViewController.mm
- Source/ui_ios/SettingsViewController.h
- Source/ui_ios/SettingsViewController.mm
- Source/ui_qt/Qt_ui/settingsdialog.ui
- Source/ui_qt/mainwindow.cpp
- Source/ui_qt/settingsdialog.cpp
- Source/ui_qt/settingsdialog.h
- build_android/src/main/res/values-zh/strings.xml
- build_android/src/main/res/values/donottranslate.xml
- build_android/src/main/res/values/strings.xml
- build_android/src/main/res/xml/settings_emu_fragment.xml
Notes:
~~Windows: UI needs updating, Im aware that passing some DROPDOWN flag to CListBox allows me to create a drop down menu to add resolution multipliers, but how would I create a label for it?~~
Since current Win32 UI we'll be replaced with Qt, no need to worry about this
iOS: no experience in iOS (/UI), so I can't do much about it (if it even has the option now for higher resolution?)
Qt: tested on OSX/Win32 works fine
~~Android: 👍, though I noticed some indentation inconsistency in the xml, so will fix that.
edit:
for android I noticed you're using `CSettingsManager` which then calls `CAppConfig`, is that necessary?~~
> Resolution Multipliers

- Source/ui_shared/BootablesProcesses.cpp
extra / causes cdn to create a unique cache to that url, which we over TGDB dont actually clear when new image is uploaded
> fix cover art url string formatting

- .travis.sh
- Source/ui_qt/CMakeLists.txt
- installer_unix/Play.desktop
an amalgamation of #628 (app image) #543 (install)
for testing initially built on Ubuntu 16.04 (using Qt 5.12):
resulting package tested on Ubuntu 16.04, arch linux (PS4) (dont know how versioning work on arch XD)
Note: I can't test travis deployment, but assuming its straight forward, that should work just fine as committed
resolves #635 closes #628 closes #543
> Linux deployment

- Source/ui_qt/vfsdiscselectordialog.cpp
related to #806 
note, this still doesnt allow games to start from disc on windows, since i think `COpticalMedia` can't create a valid stream from cdvd physical address? (atleast for the games i've tested)
> allow selecting cdfs as disc type

- .travis.sh
- .travis.yml
- Source/ui_qt/GSH_OpenGLQt.cpp
- Source/ui_qt/openglwindow.cpp
this will only build Qt GLES Arm64 version on travis, it will not deploy it.
to deploy it, we need to build `linuxdeployqt` from source, since no prebuilt version currently exist, however thats currently causing me issues, since it builds, but refused to package due to the current glibc version (since they want to "encourage" use of older version for compatibility reasons).
edit:
the header problem stems from clash of GLEW/Qt vs GLES/Qt so there was no configuration that would work for all of them
> Arm64 travis

- .travis.sh
closes #830 
`linuxdeployqt` doesnt like xenial glibc version, so we must use `-unsupported-allow-new-glibc`,
however, that param still doesnt allow us to package an image, as it expect us to package `glibc`,
but it only checks for `appdir/usr/share/doc/libc6/copyright`.
Note:
we could build on trusty to avoid the work around, but that would net us nothing.
as `-unsupported-allow-new-glibc` does nothing more than skip a check (nothing more or less is packaged)
https://github.com/jpd002/Play-/compare/e4be67948255e207a299a6b3881c77cd546c290c...84c6697b437fdd122d8769440b960a91d311ce51?expand=1
> remove libc from AppImage

- Source/CMakeLists.txt
- Source/iop/DirectoryDevice.cpp
- Source/iop/Iop_McServ.cpp
- Source/iop/Iop_McServ.h
- Source/iop/Iop_PathUtils.cpp
- Source/iop/Iop_PathUtils.h
- tools/McServTest/Main.cpp
as far as i can tell, these seem to be the only problematic lines, ill do another sweep later.
if device path starts with "/" the combined path truncates all of basePath except for partition part...
on windows
```cpp
std::filesystem::path basePath = "C:\blah\blash\blah";
char* devicePath = "/evil_access";
basePath / devicePath == "C:\evil_access";
```
Linux:
https://coliru.stacked-crooked.com/a/76ffae7f68e39128
~~Note: need to test this fix on Linux/OSX~~
Note to self:
fixes in `IOP_McServ` can probably just use `MakeHostPath()` instead
> Fix path builder

- Source/ui_ios/Purei_Prefix.pch
Boost has already been removed from the project, but this include somehow lasted and was causing an error if boost was not available.
This file could probably be removed anyway since it hasn't been updated.
> Remove boost dependency

- Source/gs/GSH_OpenGL/GSH_OpenGL.cpp
- Source/gs/GSH_OpenGL/GSH_OpenGL.h
- Source/gs/GSHandler.cpp
- Source/gs/GSHandler.h
I've noticed that this PR, this code block below is now duplicated between `GetScreenshot()`, and both `FlipImpl()` in OpenGL and Vulkan, perhaps its best to abstract it into the `CGSHandler`, as these are they're graphics api independent (function name suggestions? `PopulatePS2DisplayInfo(DISPFB& fb, DISPLAY& d)`)
```cpp
DISPFB fb;
DISPLAY d;
std::lock_guard<std::recursive_mutex> registerMutexLock(m_registerMutex);
unsigned int readCircuit = GetCurrentReadCircuit();
switch(readCircuit)
{
case 0:
fb <<= m_nDISPFB1.value.q;
d <<= m_nDISPLAY1.value.q;
break;
case 1:
fb <<= m_nDISPFB2.value.q;
d <<= m_nDISPLAY2.value.q;
break;
}
```
> capture screenshot directly from display framebuffer, at rendering resolution

- Source/PS2VM.cpp
- Source/gs/GSHandler.cpp
- Source/gs/GSHandler.h
- Source/ui_qt/PreferenceDefs.h
- Source/ui_qt/Qt_ui/settingsdialog.ui
- Source/ui_qt/mainwindow.cpp
- Source/ui_qt/mainwindow.h
- Source/ui_qt/settingsdialog.cpp
- Source/ui_qt/settingsdialog.h
Note:
```I think ideally we'd have a function `CGSHandler::Swap(gs)` that would copy memory/regs over, and swap the reset of the states, however, right now, all of these are protected, so this was the easiest way, without moving everything around.```
edit: it seems i misunderstood how protected members work, they can actually be accessed just fine by another instance of the same class.
Tested:Win32
Games: KH, FF12, MX8
MX8 produces weird artifacts at the bottom when swapped during dialog
videos on discord
overlay is MSI afterburn
> Vulkan toggle

- Source/CMakeLists.txt
- Source/InputConfig.cpp
- Source/InputConfig.h
- Source/input/InputBindingManager.cpp
- Source/input/InputBindingManager.h
- Source/ui_qt/ControllerConfig/controllerconfigdialog.cpp
- Source/ui_qt/ControllerConfig/controllerconfigdialog.h
- Source/ui_qt/PreferenceDefs.h
- Source/ui_qt/Qt_ui/controllerconfigdialog.ui
- Source/ui_qt/mainwindow.cpp
~~this PR would require these changes https://github.com/jpd002/Play--Framework/commit/3ab44ec526647666ebdd73f95dcce8ed6da9f8e9 in Framework repo.~~
~~however, I'm not sure how you feel about those particular changes? more specifically the `Framework` ones? making path editable and Load accessible like that.~~
I also moved gamepad config to their own xml, i know a while back, you didnt really want that, under slightly different context (aka gamepad1 vs gamepad2), however in this case, i think the config file will be overflooded and harder to manage if we keep all the profiles in the same `config.xml` file
TODO:
~~- [ ] add few error msg dialogs~~
~~- [ ] clean up commits, use descriptive names~~
> Gamepad profile

- Source/iop/Iop_Cdvdfsv.cpp
I found this through logs, if you try to run OSDSYS from bios, it will print these details.
`sceCdInit: cdvdfsv Ver 0000 cdvdman Ver 0000`
> document CCdvdfsv::Invoke592 method 0 structure

- Source/iop/IopBios.cpp
- Source/iop/IopBios.h
- Source/iop/Iop_Vblank.cpp
- Source/iop/Iop_Vblank.h
I pieced together what the function is supposed to do via [SLUS-20145](https://github.com/jpd002/Play-Compatibility/issues/1089), and looking at the [[RO]man](http://lukasz.dk/playstation-2-programming/archive/) implementation of the VBlank module.
No other game in my collection uses this method, but it fixes music playing to fast in SLUS-20145, So I guess its the right direction.
> Add ReleaseVblankHandler

- Source/gs/GSH_Direct3D9/GSH_Direct3D9.cpp
- Source/gs/GSH_OpenGL/GSH_OpenGL.cpp
- Source/gs/GsTextureCache.h
The problem fixed here is the following:
DBZ Budokai Tenkaichi 2 and 3 (at least) use textures, which have a buffer width of 0. This caused the texture cache to get confused, as it effectively build a 0 pixel wide rect.
The other thing that baffled me was the fact that these games also use 0 length "host to local" data transfers. This triggered an assert downstream (since it found an dirty page, but due to the 0 transfer width, there was nothing to actually set dirty).
I don't really see how these textures even work with a 0 buffer size, but they seem to (note, the textures in the menu of Tenkaichi 2 are also kinda animated).
Unrelated: Unfortunately, Tenkaichi 2 still has the all-black texture for characters problem... But I have a hunch what the problem is.
**Screenshots (Tenkaichi …
> Account for textures with 0 buffer width

- .travis.sh
the arm64 build seem to have 32 threads at their disposal, so why not use them :)
I checked other builds, this doesn't seem to have any effect, likely due default parallel building.
edit: didn't test android, though I'm not sure how we'd pass this to it, or if we even should, since we don't interact with cmake directly.
> travis linux parallel build

- Source/iop/Iop_Cdvdfsv.cpp
- Source/ui_shared/CMakeLists.txt
It wasn't too clever not commenting out `ret[N];`
and `nlohmann_json` warning was too verbose.
1 other waring silenced here, https://github.com/jpd002/Play--Framework/pull/28, I can include the repo update here once merged.
> Silence Warnings

- Source/ui_libretro/CMakeLists.txt
As mentioned in #891 a Linux build of the Play libretro core with gcc-8 will crash because of an unknown symbol
`retroarch: symbol lookup error: /usr/local/lib/libretro/play_libretro.so: undefined symbol: _ZNSt10filesystem7__cxx114path14_M_split_cmptsEv`
The issue seems to be specific to gcc-8 and the attached changes fix it.
> Fix symbol error when building libretro core with gcc-8

- Source/iop/DirectoryDevice.cpp
- Source/iop/DirectoryDevice.h
- Source/iop/Ioman_Device.h
- Source/iop/Iop_FileIoHandler1000.cpp
- Source/iop/Iop_Ioman.cpp
- Source/iop/Iop_Ioman.h
- Source/iop/OpticalMediaDevice.cpp
- Source/iop/OpticalMediaDevice.h
Implements some small memory card related improvements.
The 0 / -1 switch on CMcServ::GetInfo is just niceness - I don't think any game or homebrew actually relies on this behavior.
The Mkdir call is used by the PS2SDK memory card example, and partially fixes that example.
> Small mc improvements

- Source/ee/VUShared.cpp
RNEXT behaviour now matches the hardware test results
I found the behaviour here https://web.archive.org/web/20060908233922/http://project-fao.org/doc/rnd.html which was linked to in PCSX2 source.
> improve VU MOVE/RNEXT instruction

- Source/gs/GSH_OpenGL/GSH_OpenGL.cpp
~~This PR fixes two visual bugs in DBZ Budokai, distinct by commit:~~
~~Firstly, it implements a missing blend mode, required for some kinda minigame (dunno how to call this otherwise :D).~~
**Edit**: This PR was adjusted, to only contain the changes mentioned below. The blend-mode commit was removed, as a proper fix will be implemented elsewhere.
The second regards the transparent junk in the background during battle:
If we do a local to local transfer, the destination might not be a framebuffer, but a texture. This is used in the game for some "depth of field" effect during battle.
> Fix rendering issues in DBZ Budokai

- .travis.sh
- .travis.yml
- Source/ui_qt/CMakeLists.txt
- Source/ui_qt/unix/GamePadDeviceListener.cpp
- Source/ui_qt/unix/GamePadInputEventListener.cpp
Muahaha a lucky break as Travis has recently added FreeBSD support (even documentation isn't up yet) 👿 BSD
few notes
- FreeBSD travis image seems to contain gcc 10, which is causing build problems, mostly due to ["Reduced header dependencies, leading to faster compilation for some code"](https://gcc.gnu.org/gcc-10/changes.html), which we will need to address eventually.
- I don't really know how the packaging system work on FreeBSD systems yet, so for now, CI will just be used to ensure no breaking changes are introduced
TODOs:
- we crash when opening controller dialog, Qt 5.14 issue, caused by `QGroupBox` replacing it with `QFrame` fixes the crash (not sure if we should just drop `QGroupBox` or wait and see if its fixed upstream?)(since we're not doing releases, this is a non issue)
- …
> FreeBSD CI

- Source/ui_qt/unix/GamePadDeviceListener.cpp
- Source/ui_qt/unix/GamePadInputEventListener.cpp
According to the manpage:
Note well: Upon return, each of the file descriptor sets is modified in place to indicate which file descriptors are currently "ready".  Thus, if using **select() within a loop, the sets must be reinitialized** before each call. 
The implementation of the fd_set arguments as value-result arguments is a design error that is avoided in poll(2) and epoll(7).
So, I've moved the FD_ZERO and the FD_ZET into the loop itself before the `pselect` call
> fix pselect usage

- Source/ui_android/java/com/virtualapplications/play/database/GameIndexer.java
This should add support to discover games that are saved on a CIFS share folder mounted to the android device(Nvidia Shields have this functionality).
My shield(32 bit not fast enough?) is not good at running this emulator so this may need more testing before merge to ensure CIFS has the speed needed to load the ROMs fast enough for the emulator.
> Add CIFS mount support for Android clients

- Source/iop/OpticalMediaDevice.cpp
Mafia tries to open a file on disc as RW, and expects it to work.
This PR allows the game to save, and thus get into gameplay. Altho there are still other issues with the game.
> Don't care for mode on reading files from optical media

- .travis.sh
- appveyor.yml
Link for SDK seems to have changed.
the window build was uneffected, since its using cached version.
> update vulkan sdk download link

- Source/DiskUtils.cpp
fix cue/bin path concat on windows for S3, on windows the path will look like /s3/bucket\game.bin so aws s3 can't find the game
> Fix: Windows S3 AWS BIN

- .github/workflows/build-android.yaml
- .github/workflows/build-ios.yaml
- .github/workflows/build-linux.yaml
- .github/workflows/build-macos.yaml
GitHub actions fail on my fork, since it tries to upload artifcats to S3, added few checks to stop that,
I've also added action to upload to github artifacts, both useful for branches and forks.
P.S I also dont like how each job is its own workflow, because of that, each branch creates 4 different workflows, and all the artificats are inside each workflows, as oppose just 1 workflow with multiple jobs.
e.g i joined up all thwe work flows into 1, and now all the artifcats are listed under 1 workflow here https://github.com/Zer0xFF/Play-/actions and if you look at the workflow list, its 1 action for all of them https://github.com/Zer0xFF/Play-/actions/runs/421228891 with a workflow like this, you can introduce a new dependent job that you can use to automatically trigger aws update (since …
> GitHub actions

- Source/PS2VM.cpp
- Source/PS2VM.h
- Source/ui_libretro/GSH_OpenGL_Libretro.cpp
- Source/ui_libretro/main_libretro.cpp
to elaborate a bit on this fix,
so when running in single thread gs mode, during VM's handler destruction, the VM uses its mailbox to queue the handler destruction action, however, since the GS is not threaded, the VM mailbox can already be blocked, by a blocking call to the GS, leading to a deadlock.
so the initial solution was, to destroy the GS 1st, then start VM destruction, which worked fine for the most part, but that ran into issues, (1) between calling `gs->Release()` -> `delete gs;` a call could have already been queued up, and blocked VM mailbox (thus we needed 884ccc2)
2) we successfully delete gs, but segfault instead, since between `delete gs;` and `vm->->Pause()`, the DMA/GIF tried to send cmd to a destroyed GS...
so the easier solution was, to swap the GS on the fly, with a …
> Libretro fix

- Source/gs/GSH_OpenGL/GSH_OpenGL.cpp
glCheckFramebufferStatus is called in release when the result is only used for an assertion.
Moving this into the assertion gives a noticeable speed increase.
In Baldurs Gate Dark Alliance, on the bartender dialog scene (first dialog of the game) this give an FPS increase from 40fps to 53 fps on my machine.
> remove assertion code in release

- Source/gs/GsPixelFormats.h
The m_pageOffsetsInitialized flag is not used in the 2 template specialisation functions for 4 and 8bpp. That makes constructing the PixelIndexer object expensive.
The speedup is modest but worthwhile .. approx 10% in my testing 40fps -> 44fps in my Baldurs Gate test scene.
> correctly use initialisation flag

- Source/gs/GSHandler.cpp
Fixes the ["PS2 Coding is good for you" Homebrew Demo](http://www.pouet.net/prod.php?which=32469).
Turns out, the game never sets any of the 3 mentioned registers, and assumes them to be set correctly. My guess is, that this happens via the BIOS on console, either implicitly (not getting reset) or explicitly (based on PAL/NTSC of game, etc.).
The values are calculated via [GsSetDefaultDisplayEnv from ps2sdk](https://github.com/ps2dev/ps2sdk/blob/3c4e3ef0df01c49bdb4620c32d3496eeab5f7f81/ee/libgs/src/draw.c#L74), and is correct for NTSC, interlacing and fullframe.
> Set correct defaults for SMODE, DISPLAY 1 and 2.

- Source/gs/GSH_OpenGL/GSH_OpenGL.h
- Source/gs/GSH_OpenGL/GSH_OpenGL_Texture.cpp
Needs work .. needs an ARM Neon implementation. Also should implement for the other pixel formats.
Still, the result is impressive locally.
master:
with PR:
> SSE version of column unswizzle for PSM8

- Source/gs/GSH_Vulkan/GSH_VulkanTransferHost.cpp
> Fix Virtua Fighter 4 character selection screen on the Vulkan renderer

- Source/gs/GSH_OpenGL/GSH_OpenGL.cpp
- Source/gs/GSH_OpenGL/GSH_OpenGL.h
- Source/gs/GSH_OpenGL/GSH_OpenGL_Shader.cpp
When a alpha test fail method is set, and the trivial cases cannot be handled via color mask, we need to handle it in shader code.
TODO: This implementation based on framebuffer fetch, and thus only works on mobile. Also, this does not correctly handle cases where no depth should be written to the framebuffer.
> Partially implement TEST_1/2 AFAIL on mobile via framebuffer fetch

- Source/gs/GSH_Vulkan/GSH_Vulkan.cpp
- Source/gs/GSH_Vulkan/GSH_VulkanMemoryUtils.cpp
- Source/gs/GSH_Vulkan/GSH_VulkanMemoryUtils.h
- Source/gs/GSH_Vulkan/GSH_VulkanTransferHost.cpp
- Source/gs/GSH_Vulkan/GSH_VulkanTransferLocal.cpp
requires https://github.com/jpd002/Nuanceur/pull/3 https://github.com/jpd002/Play--Framework/pull/31
this has shown promising results in few games I've tested
MX8
Master: 40fps
PR: 94fps
Kingdom Hearts
Master: 60fps
PR: 100fps
FFXII
Master: 18fps
PR: 26fps
these changes have negative impact when used fragment shader (aka `GSH_VulkanDraw.cpp`), in MX fps would drop back to about 40fps, (with some added artifcats?).
whats missing is mostly PSMT4 support, i believe FFXII (& Champions of Norrath) uses those heavy, so there is a performance to be gained there, though im not ensure sure how to go about it.
> [WIP] Vulkan: use 8/16 bit writes when possible

- Source/gs/GSH_OpenGL/GSH_OpenGL_Shader.cpp
Currently, on master, we have two scenarios:
Firstly, if we can use the framebuffer fetch extension, alpha test fail is implemented mostly correctly (cases which should prevent writing depth are not handled correctly). If we don't have access to the extension, we discard the write on test failure completely.
This PR tackles the second case. Specifically `ALPHA_TEST_FAIL_FBONLY` (only write color and alpha, but no depth). This change allows the pixel to be written with color, alpha and depth in full. While this is not correct (it should not write depth), this is better than discarding the pixel write completely, and actually fixes quite some games (I will add screenshots later). `ALPHA_TEST_FAIL_RGBONLY` is basically the same thing (writing all three components), when it should only write …
> Make AFAIL a bit more lenient on desktop

- Source/ee/Ee_LibMc2.cpp
- Source/ee/Ee_LibMc2.h
Remove the assert for unmatched function calls, and instead log all unmatched functions as warnings
> Clean up LibMC2 warnings

- Source/iop/Iop_Sysclib.cpp
- Source/iop/Iop_Sysclib.h
Makes sysclib's `memcpy` use `GetPtr` for address sanitation, and implements IOP ram mirroring in said function.
Makes Max Payne 2 not segfault before going into menu on desktop, and makes menu music in that game work in general.
> Sysclib memcpy address sanitation

- Source/ui_android/java/com/virtualapplications/play/Constants.java
- Source/ui_android/java/com/virtualapplications/play/SettingsActivity.java
- Source/ui_android/java/com/virtualapplications/play/settings/EmulatorSettingsFragment.java
- Source/ui_android/java/com/virtualapplications/play/settings/UISettingsFragment.java
- build_android/src/main/res/values/styles.xml
- build_android/src/main/res/xml/preferences_emu.xml
- build_android/src/main/res/xml/preferences_ui.xml
- Fix preference that somehow got itself out of order during my AndroidX Preference PR
- Use the (relatively) new simple summary provider feature (introduced in [this](https://developer.android.com/jetpack/androidx/releases/preference#version_110_3) version)
- Rename old checkBox names to switch
- Make all themes use one common parent
- Create a colorAccent, which will theme stuff like dialogs and settings. This gets rid of the outdated holo blue that's still visible in several locations.
- For the above to apply correctly to settings, the settings activity needs to be recreated with the new theme whenever it is changed. The `setDefaultValues` is for this reason:
- The settings' default values are first set when its XML layout is inflated for the first time. So when the UI settings layout …
> [Android] Preference and theming improvements

- Source/ee/PS2OS.cpp
Includes two fixes:
- Adjustment for `CIopBios::TryGetImageVersionFromPath` to be case insensitive, as the game calls it with `rom0:UDNL host0:ioprp300.img` - note the lowercase
- ~Basic re-mapping in `Ioman::PreOpen` to try to find files in cdrom0, if they cannot be found in host0. The game expects to find its data files in host0.~
- Upon loading the executable, A0 is set to the entrypoint address. The game relies on this (undefined behavior).
> Fixes for Darkwatch

- Source/ui_ios/Base.lproj/Main.storyboard
- Source/ui_ios/EmulatorViewController.mm
- Source/ui_ios/PreferenceDefs.h
- Source/ui_ios/SettingsViewController.h
- Source/ui_ios/SettingsViewController.mm
- Source/ui_ios/VirtualPadButton.mm
- Source/ui_ios/VirtualPadView.mm
Some small improvements:
- Added preference for Virtual Pad opacity
- Added preference for hiding the virtual pad when a controller is connected
- Added a section for Virtual Pad in Settings
- Added haptic feedback for Virtual Pad and settings to enable it
- Add support for L3/R3 buttons for external controllers (requires iOS 12.1+)
- Add support for Select/Start buttons for external controllers (requires iOS 13+)
I can merge master after PR #1097 is merged (right now it has those diffs)
> [iOS] Quality of Life Improvements: Virtual Pad transparency/auto-hide, L3/R3/Select/Start buttons for controllers

- Source/CMakeLists.txt
- tools/VuTest/VuAssembler.h
Modern versions of `gcc` and `clang` require these changes to compile.
see: https://reviews.llvm.org/D86936
> Fix compile errors

- Source/CMakeLists.txt
This prevents installing dependency files with cmake.
```
[1/1] Installing the project stripped...
-- Install configuration: "None"
-- Installing: /tmp/build/install/Play-/bin/Play
-- Installing: /tmp/build/install/Play-/share/icons/hicolor/1024x1024/apps/Play.png
-- Installing: /tmp/build/install/Play-/share/icons/hicolor/scalable/apps/Play.svg
-- Installing: /tmp/build/install/Play-/share/applications/Play.desktop
-- Installing: /tmp/build/install/Play-/include
-- Installing: /tmp/build/install/Play-/include/ghc
-- Installing: /tmp/build/install/Play-/include/ghc/filesystem.hpp
-- Installing: /tmp/build/install/Play-/include/ghc/fs_fwd.hpp
-- Installing: /tmp/build/install/Play-/include/ghc/fs_impl.hpp
-- Installing: /tmp/build/install/Play-/include/ghc/fs_std.hpp
-- Installing: …
```
> cmake: Use EXCLUDE_FROM_ALL for add_subdirectories

- CMakeLists.txt
This fixes some problems.
* `git describe` without `--always` can fail in shallow clones.
* git will end up working in the wrong directory when doing an out of tree build.
* git may not actually be installed
* The `.git` directory may not be present, for example the user can download a source archive from any github branch, tag or commit where the git history will not be included.
> cmake: Better git handling

- CMakeLists.txt
- Source/ui_qt/CMakeLists.txt
This is helpful for distros and anyone installing to a non-standard potentially arbitrary location. For example a distro may want `/usr/games/Play` rather than the default of `/usr/bin/Play` and can configure this with `-DCMAKE_INSTALL_BINDIR=game`.
Reference: https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html
I also reformatted it for better readability.
> cmake: Use GNUInstallDirs

- Source/ui_shared/BootablesDbClient.cpp
this conditional limitation is not needed, as it breaks filtering with none-states.
> Qt State: fix condition

- Source/iop/ioman/OpticalMediaDevice.cpp
Fixes Constantine not booting.
I'm not entirely sure if this is the most elegant solution, but it works. The alternative could be to store the root entry via "." instead of "", but maybe this could break other games?
> Handle retrieving root file record via dot

- Source/iop/Iop_Cdvdman.cpp
- Source/iop/Iop_Cdvdman.h
On first invocation of CdTrayReq, return 1 for a check request (which indicates a new disc).
Allows Iron Man to boot (probably playable, but its very slow).
> Inform about new disc via CdTrayReq

- Source/iop/Iop_McServ.cpp
- Source/iop/Iop_McServ.h
When https://github.com/jpd002/Play-/pull/1190 is merged, 007 Agent Under Fire does crash on startup. With this fix, the game can go in-game with okayish performance.
Note, savegame saving works, but loading does not :(
> Ignore McServ ChDir commands with invalid port or slot

- patches.xml
Removed the no longer needed "Disable NET SIF bind" patch for the game "Outrun 2006: Coast 2 Coast" (U)
> Removing Outrun patch

- patches.xml
It was used for debugging purposes in the past, no longer needed to make the game work properly
> Removed the Baldur's Gate patch

- Source/ee/Ee_SubSystem.cpp
Results seem to be good when a load is triggered within the same area,
FFXII areas are big and you can be in either ends of the area and loading is almost instant.
however, loading from different areas is still slowish.
~~I've noted few instances where the emu would "load" a save state, but the game doesn't resume correctly, I was able to reproduce the issue once on master, but not in a consistent way yet.
so marking as WIP until i can confirm the issue.~~ I was able to reproduce the issue with few different build combo, so its very unlikely to be directly caused by this change.
> when loading a save state, only invalidate changed EE blocks

- Source/iop/Iop_NamcoArcade.cpp
- Source/iop/Iop_NamcoArcade.h
- Source/ui_shared/ArcadeUtils.cpp
- arcadedefs/acedriv3.arcadedef
- arcadedefs/motogp.arcadedef
- arcadedefs/rrvac.arcadedef
- arcadedefs/wanganmd.arcadedef
- arcadedefs/wanganmr.arcadedef
Add drive inputmode.
Add jvs analog for drive inputmode (limiting to LSY+ for accel and to RSX+ for brake).
Add jvs coin managment despite never receiving jvs coin inc/dec cmd.
Resolve missing button4 (tekken) (located on R3).
Latching test button.
Just added acedriver3 arcadedef file (not my work).
> N246 additions

- Source/ui_qt/DebugSupport/FrameDebugger/PixelBufferView.cpp
- Source/ui_qt/DebugSupport/FrameDebugger/QtFramedebugger.cpp
- Source/ui_qt/DebugSupport/MemoryViewTable.cpp
- Source/ui_qt/Qt_ui/s3filebrowser.ui
- Source/ui_qt/S3FileBrowser.cpp
- Source/ui_qt/S3FileBrowser.h
- Source/ui_qt/memorycardmanagerdialog.cpp
few changes to allow forward compatability with Qt6.
though we probably dont want to move to it anytime soon, 32bit prebuilds has been dropped (though I dont believe official support is dropped, yet, so we can build from source (or wait until someone eventually does XD)).
to build with Qt6, you'd need to replace emu ui + debugger ui cmake `Qt5` & `QT5` replaces with `Qt6` & `QT6`
> Qt6 compatibility

- Source/iop/Iop_NamcoArcade.cpp
I'm not sure what manual https://www.arcade-projects.com/threads/yet-another-256-display-issue.2792/#post-37365 is from, but they appear to have gotten the setting for switch 4 wrong; OFF sets composite sync, and ON sets separate sync. The diagram above even correctly shows this, as all (or at least most) games shipped with all switches set to off for 15khz, and switches 2-4 are all meant to be flipped up for 31khz. Backed up against the F/UC operator's manual (link at https://www.arcade-projects.com/threads/fate-unlimited-codes-japanese-manual-pdf.7799/, direct link https://mega.nz/#!shwzSY5K!E1gzeJaA6oGHNqARNBvsmJB1LlsF6qO6Z9Ke4vLQJ_U in case it's taken down)
> Fix dipswitch documentation

- arcadedefs/idolm.arcadedef
- arcadedefs/idolmtower.arcadedef
Added the arcadedefs that are working right now for Idolm@ster. It shares the same HDD with the two types of cabinet of the game, as the dongle is the responsible for deciding which version will it run (Tower or Station).
The main game happens in the Station cabinet, while the Tower shows the nationwide rankings runs a permanent Attract Mode.
As it goes, the Tower functions even without the implementation of Touchscreen support, while the Station still needs the Card RW module and Touchscreen support to be played.
> Add Idolm@ster arcadedefs

- Source/MailBox.cpp
This might have some performance ramifications, since previously all waits got released once a single call finished.
having said that, I do think emu thread is the only thread that calls on GS, so if its waiting, calling all or once is all the same and will have no impact or notable change at that.
> Fix Mailbox potential race condition

- Source/input/InputBindingManager.cpp
- Source/input/InputBindingManager.h
- Source/input/InputProvider.h
- Source/ui_js/InputProviderEmscripten.cpp
- Source/ui_qt/ControllerConfig/inputeventselectiondialog.cpp
- Source/ui_qt/ControllerConfig/inputeventselectiondialog.h
- Source/ui_qt/InputProviderQtKey.cpp
- Source/ui_qt/InputProviderQtMouse.cpp
- Source/ui_qt/macos/InputProviderMacOsHid.cpp
- Source/ui_qt/unix/InputProviderEvDev.cpp
Change `OnInput` from a functional pointer to signal, for our use case, signals are better, since they're mutex protected (thread safe), thus reduce race chance, they simplify the code (no (explicit) guarding required), and allows multiple targets to request input.
In Framework, we also added a new call `CSignal<>::ConnectOverride(...)`, which can be used to temporarly redirect events (e.g when configuring gamepads).
Requires: https://github.com/jpd002/Play--Framework/pull/40 (would need to rebase once that is merged)
Notes: tested on Windows only (changes are simple that if it compiles, we should be fine)
> Update on input

- Source/MailBox.cpp
- Source/MailBox.h
1) remove `m_callFinished`/`m_callDone`
* future will now handle the waiting
2) `sync` replaced with `promise`
* simplify sync logic
* delegating the logic to the future (if was created)
> Moderanise Mailbox to use promises and futures

- .github/workflows/build-android.yaml
- .github/workflows/build-ios.yaml
- .github/workflows/build-linux.yaml
- .github/workflows/build-macos.yaml
- .github/workflows/build-windows.yaml
- .github/workflows/build-windows_psf.yaml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> ci: Use GITHUB_OUTPUT envvar instead of set-output command

- README.md
Noticing from reading the readme. I saw that it mentioned needing a paid developer account for debugging the app. You do not need one at the moment. I’m not sure even if there was a time that you needed one for debugging the app. You also don’t need a paid dev account for using the app or compiling it.
I changed these to reflect how using Xcode is currently. It also describes detaching the debugger to act like how the jit enablers do it which is just the detach button.
> Change Xcode debugging note in README

- Source/ui_ios/CoverViewController.mm
Results in large loading times on jailbroken devices and causes some devices to hang.
Probably something that shouldn't be done on launch, maybe have this as a manual button/toggle inside the app?
Fixes https://github.com/jpd002/Play-/issues/1227
> Don't scan /private/var/mobile

- .gitlab-ci.yml
- Source/ui_libretro/ext/libretro.h
- Source/ui_libretro/main_libretro.cpp
Similar to the flycast core, I've added a check that retroarch does on iOS to see if JIT is likely to work, and fail to load the game if JIT is not enabled.
In order to pick up that environ flag, I had to pull in a newer version of libretro.h. There shouldn't be any functional change, but the diff looks abnormally large because 1) it's been a while and 2) it looks like there was code style formatting applied to the play! version?
> Build libretro core for iOS

- Source/MIPS.h
- Source/ee/Vpu.cpp
- Source/ee/VuBasicBlock.cpp
- Source/ee/VuBasicBlock.h
- tools/VuTest/CMakeLists.txt
- tools/VuTest/IntBranchDelayTest3.cpp
- tools/VuTest/IntBranchDelayTest3.h
- tools/VuTest/Main.cpp
implements the VU edge case where an integer altering instruction is in the delay slot of a conditional branch and the first instruction following it is another conditional branch based on that integer register.
The original code will take the value of the integer register at that time assuming a pipeline shortcut but that is wrong because having an integer altering instruction directly before a conditional branch on that same integer register causes the pipeline to fail and we need to use the value most recently written to memory.
Can potentially break a lot of games so needs quite a bit of testing.
> Gauntlet 7 sorrows

- Source/ee/IPU.h
Add missing header `algorithm` for `std::clamp`
```
/build/libretro-play/src/libretro-play/Source/ee/IPU.cpp: In member function ‘virtual bool CIPU::CCSCCommand::Execute()’:
/build/libretro-play/src/libretro-play/Source/ee/IPU.cpp:1965:51: error: ‘clamp’ is not a member of ‘std’
1965 |                                         nR = std::clamp(nR, 0.f, 255.f);
|                                                   ^~~~~
/build/libretro-play/src/libretro-play/Source/ee/IPU.cpp:1966:51: error: ‘clamp’ is not a member of ‘std’
1966 |                                         nG = std::clamp(nG, 0.f, 255.f);
|                                                   ^~~~~
/build/libretro-play/src/libretro-play/Source/ee/IPU.cpp:1967:51: error: ‘clamp’ is not a member of ‘std’
1967 | …
```
> Add missing header

- Source/ui_qt/CMakeLists.txt
This is needed to compile on NetBSD, OpenBSD, illumos, etc.
> qt: Allow compiling on Unix-likes without EVDEV

- Source/ee/PS2OS.cpp
std::max expects both arguments to be the same type (in this case const char *), while the C version of strrchr returns non-const char *, which results in a type error with some C libraries.
> Fix a compilation error on some platforms.

- Source/iop/namco_sys147/NamcoSys147NANDReader.cpp
Hi, the patch solve this error found while compiling from the latest commit
This is happening on Arch Linux with GCC 14.2
```
[ 59%] Building CXX object Source/ui_qt/Source/CMakeFiles/PlayCore.dir/iop/namco_sys147/Iop_NamcoSys147.cpp.o
[ 59%] Building CXX object Source/ui_qt/Source/CMakeFiles/PlayCore.dir/iop/namco_sys246/Iop_NamcoAcCdvd.cpp.o
In file included from /usr/include/c++/14.2.1/cassert:44,
from /home/fabio/Dev/Github/PKGBUILD-AUR_fix/p/play-emu-git/src/play-emu/Source/iop/namco_sys147/NamcoSys147NANDReader.cpp:2:
/home/fabio/Dev/Github/PKGBUILD-AUR_fix/p/play-emu-git/src/play-emu/Source/iop/namco_sys147/NamcoSys147NANDReader.cpp: In member function 'Namco::CSys147NANDReader::Directory Namco::CSys147NANDReader::ReadDirectory(uint32)': …
```
> Add missing include <cstring> in NamcoSys147-NANDReader.cpp

- .github/workflows/build-android.yaml
- .github/workflows/build-ios.yaml
- .github/workflows/build-linux.yaml
- .github/workflows/build-macos.yaml
- .github/workflows/build-windows.yaml
- .github/workflows/build-windows_psf.yaml
actions/upload-artifact@v3 is being Deprecated at the end of the month  see https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/  so i move its to the next version 
hopefully this dosent break anything , but it shouldn't
> CI : update upload-artifact version

- Source/CMakeLists.txt
- Source/app_shared/CMakeLists.txt
- Source/discimages/ChdCdImageStream.cpp
- Source/discimages/ChdStreamSupport.cpp
- Source/gs/GSH_Direct3D9/CMakeLists.txt
- Source/gs/GSH_OpenGL/CMakeLists.txt
- Source/gs/GSH_OpenGLWin32/CMakeLists.txt
- Source/gs/GSH_Vulkan/CMakeLists.txt
- Source/ui_android/CMakeLists.txt
- Source/ui_ios/CMakeLists.txt
- Source/ui_js/CMakeLists.txt
- Source/ui_libretro/CMakeLists.txt
- Source/ui_qt/CMakeLists.txt
- Source/ui_qt/DebugSupport/CMakeLists.txt
- Source/ui_shared/CMakeLists.txt
- tools/AutoTest/CMakeLists.txt
- tools/ElfView/CMakeLists.txt
- tools/GsAreaTest/CMakeLists.txt
- tools/McServTest/CMakeLists.txt
- tools/NamcoSys147NANDTools/CMakeLists.txt
- tools/PsfPlayer/CMakeLists.txt
- tools/PsfPlayer/Source/CMakeLists.txt
- tools/PsfPlayer/Source/SH_OpenAL/CMakeLists.txt
- tools/PsfPlayer/Source/ui_aot/CMakeLists.txt
- tools/PsfPlayer/Source/ui_ios/CMakeLists.txt
- tools/PsfPlayer/Source/ui_js/CMakeLists.txt
- tools/PsfPlayer/Source/ui_qt/CMakeLists.txt
- tools/PsfPlayer/Source/ui_win32/CMakeLists.txt
- tools/SpuTest/CMakeLists.txt
- tools/VuTest/CMakeLists.txt
"Requires" https://github.com/jpd002/Play--Framework/pull/46 & https://github.com/jpd002/Play-Dependencies/pull/37
(well, it doesnt actually "require" those, this can still be merged as a standalone PR, but for the cmake changes to be complete, its best to have those 2 PR merged 1st)
- Updated libchdr to upstream
- to update cmake min requirement
- includes required header fix
- Changed cmake min version to 3.18
- I removed references to  as much as possible references to `cmake_minimum_required` and `set(CMAKE_MODULE_PATH ...)`
- we can probably go a step further and also remove the `include(Header)` in the same scripts, but its probably good to have as a basic assert (if path is not set, cmake generation will fail, which will indicate an issue in cmake hierarchy)
- the reason those …
> CMake updates

- arcadedefs/batlgr3.arcadedef
- arcadedefs/batlgr37.arcadedef
- arcadedefs/batlgr38.arcadedef
- arcadedefs/batlgr3t.arcadedef
As the title suggests, I noticed in PR #1491 that the T1 count patch was implemented for battle gear 3 2.01A but not the other games. I have quickly ported these to the other arcadedefs and raised another PR (hopefully this is okay).
Have tested and works perfectly my end :)
> Port T1_COUNT patches to other battle gear 3 arcadedefs and fix hang in race mode caused by another T1_COUNT read
